{{- if .Values.config.externalSecret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-one
spec:
  refreshInterval: 30m0s
  secretStoreRef:
    name: secretstore-ibm-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.config.secret }}
    creationPolicy: Owner
  {{/* 
  data:
  - secretKey: QUARKUS_OIDC_AUTH_SERVER_URL
    remoteRef:
      key: '6e2e90e1-9f30-ccff-3b9e-39080ff715ae'
  - secretKey: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
    remoteRef:
      key: '6e2e90e1-9f30-ccff-3b9e-39080ff715ae'
  - secretKey: QUARKUS_OIDC_CLIENT_ID
    remoteRef:
      key: 'e5bd3da3-d8d0-cf05-6f78-eabf296b2ae6'
  - secretKey: QUARKUS_OIDC_CLIENT_CLIENT_ID
    remoteRef:
      key: 'e5bd3da3-d8d0-cf05-6f78-eabf296b2ae6'
  - secretKey: QUARKUS_OIDC_CREDENTIALS_SECRET
    remoteRef:
      key: '010d0d08-459a-b79e-b38f-aaa02540f068'
  - secretKey: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
    remoteRef:
      key: '010d0d08-459a-b79e-b38f-aaa02540f068'
   */}}
  dataFrom:
   - key: '841484f6-a918-e73f-93e7-459f3d5a6108'
{{- end }}