# RBAC to allow 
# - pull image from central namespace
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quarkus-playground.fullname" . }}-imagepuller-rb
  namespace: {{ .Values.config.imageNamespace | quote }}
  labels:
    {{- include "quarkus-playground.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: {{ include "quarkus-playground.serviceAccountName" . }}
  namespace: {{ .Values.config.namespace | quote }}
{{- end -}}
