# ArgoCD Configuration

config:
  names:
    base: 'argocd-demo-quarkus'
  bootstrap:
    project: demo-quarkus-app-prj
    argocdNamespace: demo-quarkus-cicd
  projects:
  - namespace: demo-quarkus-dev
    valueFile: values.dev.yaml
    branch: main
  - namespace: demo-quarkus-test
    valueFile: values.test.yaml
    branch: test
  - namespace: demo-quarkus-prod
    valueFile: values.prod.yaml
    branch: prod