# Helm chart: quarkus-playground
# Stage: dev

replicaCount: 1
stage: dev
config:
  #configmap: quarkus-playground-dev-configmap
  secret: quarkus-playground-dev-secret
  namespace: demo-quarkus-dev
  #imageNamespace: demo-quarkus-cicd


image:
  repository: image-registry.openshift-image-registry.svc:5000/demo-quarkus-cicd/quarkus-playground
  tag: latest
  pullPolicy: Always
