# Helm chart: quarkus-playground
# Stage: dev
# 
replicaCount: 1
stage: dev
config:
  #configmap: quarkus-playground-dev-configmap
  secret: quarkus-playground-dev-secret
  namespace: demo-quarkus-dev
  #imageNamespace: demo-quarkus-cicd
  externalSecret:
    enabled: true
image:
  repository: image-registry.openshift-image-registry.svc:5000/demo-quarkus-cicd/quarkus-playground
  tag: latest
  digest: sha256:0f64363bc7baadc76db6e5bd73dcab4ae7a42b224cafea70a892ee9872ed6c55
  pullPolicy: Always
ingress:
  enabled: true
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"

  basedomain: ""
  hosts:
    - subdomain: "quarkus-playground-dev-cicd"
      paths:
        - "/"
